services:
  - type: web
    name: pawsport
    runtime: docker
    plan: free
    envVars:
      - key: PETSTABLISHED_API_KEY
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false
      - key: GMAIL_RECIPIENT
        sync: false
